### ISSUE TITLE
Correct SVG definition in README

### ISSUE THREAD

**Issue by austincondiff** [PatrickAlphaC/all-on-chain-generated-nft#11]
SVG is not "scalar vector graphic", it is "scalable vector graphic". 😉 ([Reference](https://en.wikipedia.org/wiki/SVG))

Please correct [README.md](https://github.com/PatrickAlphaC/all-on-chain-generated-nft/blob/main/README.md).

**Comment by PatrickAlphaC** [comment]
Thank you! Fixed in 105b6d566576f30021984161d8e60a29bfca5dbd
