### ISSUE TITLE
error code = UNPREDICTABLE_GAS_LIMIT

### ISSUE THREAD

**Issue by vzx7** [PatrickAlphaC/all-on-chain-generated-nft#12]
Hi.
I tried to deploy with svg `/img/pug.svg` and got an error.

`
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="estimateGas", transaction={"from":"0xFB344eB59cEE6CC05add9e7C81a7e305a5400FB1","to":"0x984827822572764c4aF4335849Dbd856eC7C1D4F","data":"0x...","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)
`

How to solve this?
I'm afraid we can't calculate the gas for the transaction ...

**Comment by PatrickAlphaC** [comment]
`pug.svg` is too big, and it's just an example of what the pug svg would look like.

Sorry! You'd have to have a crazy big blockchain and it would be really expensive!

**Comment by vzx7** [comment]
Yes!
I think ipfs remains the standard for nft)
Nevertheless, I am very grateful to you for your lesson! He was really helpful!
