### ISSUE TITLE
Cant Deploy Tags

### ISSUE THREAD

**Issue by lilchoncho** [PatrickAlphaC/all-on-chain-generated-nft#13]
I am very new to coding and all these steps 

On this step:
**npx hardhat deploy --tags svg**
and Im receiving this error.

**Error HH8: There's one or more errors in your config file:

  * Invalid value {"url":"https://eth-kovan.alchemyapi.io/v2/your-api-key","accounts":{},"saveDeployments":true} for HardhatConfig.networks.kovan - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"adfsfasdf","accounts":{},"saveDeployments":true} for HardhatConfig.networks.rinkeby - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://eth-mainnet.alchemyapi.io/v2/your-api-key","accounts":{},"saveDeployments":true} for HardhatConfig.networks.mainnet - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://rpc-mainnet.maticvigil.com/","accounts":{},"saveDeployments":true} for HardhatConfig.networks.polygon - Expected a value of type HttpNetworkConfig.**

Not sure what to do here

**Comment by PatrickAlphaC** [comment]
https://ethereum.stackexchange.com/a/113156/57451

Let me know if this helps. Closing for now, feel free to follow up though!
