### ISSUE TITLE
Image changing NFTs

### ISSUE THREAD

**Issue by barkntuncer** [PatrickAlphaC/all-on-chain-generated-nft#17]
Hey Patrick!,

This might sound like a simple question. I would like to know if it's possible to make an NFT's image change on the blockchain. For example, we have an NFT featuring picture A. We would like to change the image to B whenever we want via a function in our solidity code. As I read from your description, and the sources I found online, it seems possible but I would like to hear from a professional. 

Thank you for your time! 
Best regards,
Barkin

**Comment by PatrickAlphaC** [comment]
100% possible. 

You just need to update your `tokenURI` as you need based off your parameters, and presto! Changing NFT!
