### ISSUE TITLE
[open question]: Are svg handled the same way than Aavegotchi ?

### ISSUE THREAD

**Issue by balibou** [PatrickAlphaC/all-on-chain-generated-nft#2]
Hello @PatrickAlphaC ,

Very nice repo !

 I was wondering if your approach was the same than Aavegotchi (as far as I understand ... it is not) ?

Apparently:
> It costs less gas to store SVG data as contract data than to store it in contract storage. Normally contract bytecode is stored as contract data, but it is possible to store other data as contract data, as we are doing with SVG data.

(https://docs.aavegotchi.com/overview/onchain-svgs)

Also, another question, do you think fees are sustainable to handle complex svg (let's say a picture like a knight in your D&D repo that can evolve with different items on it ... a hat, gloves, ...) or is it better to stick to an ipfs method with standard setTokenURI() ?

Thanks for your feedback ! :)

[EDIT 1]: I didn't realize but there is a youtube video for this repo :). I've just watched it and realised you've already answered to my second question with the example of the complex nft svg you've minted for 2 millions gas 😱 (https://youtu.be/nS9xP1hxg3w?t=2858). So clearly not the best option ... (right ? 😅 )

[EDIT 2]: Ok so so the real youtube video for this repo is https://www.youtube.com/watch?v=9oERTH9Bkw0 😅.  There is a question in the coments about fees and your answer was:
> They will be a little higher, but this is what you’d need to do to create customization on your NFT smart contracts

So I assume it would be possible to deploy and mint a D&D Knight on Polygon without spending a huge amount in fees ... ?

**Comment by PatrickAlphaC** [comment]
It sure would be :)

Glad you found the video!
