### ISSUE TITLE
Duplicate definition of Transfer (Transfer(address,address,uint256,bytes), Transfer(address,address,uint256))

### ISSUE THREAD

**Issue by tamphill** [PatrickAlphaC/all-on-chain-generated-nft#21]
Dear Patrick:

      I am your fan first of all!

     I git-download your code, then "yarn install", compile, deploy. It went smooth except NFT deploy token address is 0xX. I have sufficient token in rinkeby wallet. 
   1)Here is the output:
   npx hardhat verify --network rinkeby 0xF049E1Bc7C96947F015ed3F0B0cce55eD1E0d922 0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B 0x01be23585060835e02b77ef475b0cc51aa1e0709 0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311 100000000000000000
**Duplicate definition of Transfer (Transfer(address,address,uint256,bytes), Transfer(address,address,uint256))**
Let's create an NFT now!
You've made your NFT! This is number **0x0000000000000000000000000000000000000000000000000000000000000000**
Let's wait for the Chainlink VRF node to respond...

  2) Here is the event log
![image](https://user-images.githubusercontent.com/98488739/154348341-150a0c37-8ec9-4c38-a753-5aa742f3767b.png)
  
 3) The only change is during compile time, I have to add solidity version "0.6.6" and "0.8.1" otherwise keep failing.
  
![image](https://user-images.githubusercontent.com/98488739/154349133-3268c1ee-48b0-4c95-9dcc-0ac5ad628f08.png)

     I doubt version confliction somewhere.  Please advise.

Thanks

**Comment by PatrickAlphaC** [comment]
You might just have to wait longer... rinkeby has been a lot slower recently.
