### ISSUE TITLE
gas error 

### ISSUE THREAD

**Issue by nuprince** [PatrickAlphaC/all-on-chain-generated-nft#29]
Error: ERROR processing /Users//Desktop/all-on-chain-generated-nft/deploy/01_Deploy_SVGNFT.js:
InvalidInputError: Transaction gas limit is 30582296 and exceeds block gas limit of 30000000

thats the issue that comes up when i try to deploy my svg .... any way to fix this ?

**Comment by PatrickAlphaC** [comment]
Your SVG is too big. 

You'll have to make it smaller. Sorry! 

Or, you'll have to slowly append data to your tokenURI, which is a little harder. This would make a great stack exchange ETH question:

```
How can I put more data into a variable than fits into a block?
```

**Comment by nuprince** [comment]
the file is 9kb .. how small does it have to be ?

**Comment by PatrickAlphaC** [comment]
That should be small enough... 

Try this: 
https://ethereum.stackexchange.com/questions/113706/increase-block-gas-limit-hardhat?rq=1

**Comment by nuprince** [comment]
Yea I tired that before I posted it …. I’m just going the other route ….
