### ISSUE TITLE
Deployment of RandomSVG hangs for 30+ minutes

### ISSUE THREAD

**Issue by hushaudio** [PatrickAlphaC/all-on-chain-generated-nft#31]
Started the tutorial for this, and during the initial deployment tests before coding - deployment of RandomSVG hangs for 30+ minutes and does not complete or timeout.  Account has Eth and Test coin.  Using Rinkeby network just like in the tut.  SVGNFT deploys fine, no problems.  RandomSVG just hangs - screenshot bellow.

Env vars are set (accept no MAINNET_RPC_URL, because I'm not deploying to main net yet) 

using command: `npx hardhat deploy --network rinkeby --tags rsvg`

OSX 10.15.7
Macbook Pro Mid 2018

<img width="765" alt="Screen Shot 2022-05-16 at 2 54 53 PM" src="https://user-images.githubusercontent.com/54246375/168671752-0934c138-6251-4e61-b318-048746de3379.png">

**Comment by PatrickAlphaC** [comment]
Rinkeby has been pretty slow recently :( Could just be rinkeby issues.
