### ISSUE TITLE
How token is generated when we call finishMint()

### ISSUE THREAD

**Issue by barkntuncer** [PatrickAlphaC/all-on-chain-generated-nft#32]
Hey Patrick!
Thank you vm for all the information. I am a bit confused. When a person calls the finishMint() function the NFT is minted but I don't see the connection between finishMint() and `_safeMint()`. Could you please explain me how they actually interact with each other?
I am trying to write a code where the user would have to give a string input while minting the NFT. I am not sure where I should get that input
Thanks in advance

**Comment by PatrickAlphaC** [comment]
You have to call `finishMint` yourself in this example!
