### ISSUE TITLE
Does Verify need extra arguments?

### ISSUE THREAD

**Issue by stoplion** [PatrickAlphaC/all-on-chain-generated-nft#4]
`npx hardhat verify --network mumbai 0x7B4d4B5189446e5A5dC03f40F35Dd1A3B96AF740 --show-stack-traces `

```
Error in plugin @nomiclabs/hardhat-etherscan: The constructor for contracts/RandomSVG.sol:RandomSVG has 4 parameters
but 0 arguments were provided instead.
```

**Comment by PatrickAlphaC** [comment]
Did you figure it out?

**Comment by expertfox** [comment]
> `npx hardhat verify --network mumbai 0x7B4d4B5189446e5A5dC03f40F35Dd1A3B96AF740 --show-stack-traces `
> 
> ```
> Error in plugin @nomiclabs/hardhat-etherscan: The constructor for contracts/RandomSVG.sol:RandomSVG has 4 parameters
> but 0 arguments were provided instead.
> ```

what was the solution?

**Comment by expertfox** [comment]
Restarting vscode solved the issue
