### ISSUE TITLE
Pending tx on Mumbai tesnet

### ISSUE THREAD

**Issue by balibou** [PatrickAlphaC/all-on-chain-generated-nft#5]
when deploying on Mumbai testnet (`npx hardhat deploy --network mumbai --tags svg`), the transaction stays spending.

`waiting for tx 0x0de60df180d69ad61ea28725163b407efe3056ff956bcd95025e93329e725914 for SVGNFT Deployment`

I have 1 MATIC / 10 LINK in my Mumbai wallet.
I've added in the `hardhat.config.js`:
```js
mumbai: {
            url: MUMBAI_RPC_URL,
            accounts: [PRIVATE_KEY],
            saveDeployments: true,
        },
```
And in the `helper-hardhat-config.js`

```js
80001: {
      name: 'mumbai',
      linkToken: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB',
      ethUsdPriceFeed: '0x0715A7794a1dc8e42615F059dD6e406A6594651A',
      keyHash: '0x6e75b569a01ef56d18cab6a8e71e6600d6ce853834d4a5748b720d06f878b3a4',
      vrfCoordinator: '0x8C7382F9D8f56b33781fE506E897a4F1e2d17255',
      oracle: '0x58bbdbfb6fca3129b91f0dbe372098123b38b5e9',
      jobId: 'da20aae0e4c843f6949e5cb3f7cfe8c4',
      fee: '100000000000000',
      fundAmount: "100000000000000"
    },
```

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue. It's likely it's your `MUMBAI_RPC_URL`. Is that the default one? Those often have issues.

**Comment by balibou** [comment]
@PatrickAlphaC Yes it's the default one:
`MUMBAI_RPC_URL='https://rpc-mumbai.maticvigil.com`

**Comment by PatrickAlphaC** [comment]
It could just be that :/ 

You could try a different node hosting service like quicknode

**Comment by balibou** [comment]
Ah thanks @balibou , will try that now :)

**Comment by balibou** [comment]
@PatrickAlphaC, I tried with infura (I already had an account): `https://polygon-mumbai.infura.io/v3/{MY-KEY}` but still pending :/

**Comment by PatrickAlphaC** [comment]
How long did you wait?

**Comment by balibou** [comment]
Since I sent you the message (18 minutes now)

**Comment by PatrickAlphaC** [comment]
Yikes.... hmm.... Perhaps try recreating the repo? Maybe the old "off and on again" trick will work...

**Comment by balibou** [comment]
mmm don't change the result as well ...
Rinkeby is still working perfectly

**Comment by PatrickAlphaC** [comment]
It's likely to be a mumbai issue then :( 

If it's working well on Rinkeby, I wouldn't worry about testing on Mumbai. They are nearly identical in how they function. You should be able to deploy to polygon (after adding the right variables) no problem. 

I've also had mumbai issues in the past :(

**Comment by PatrickAlphaC** [comment]
Closing this issue for now, feel free to follow up.
