### ISSUE TITLE
Transaction Error. Exception thrown in contract code.

### ISSUE THREAD

**Issue by EnriqueGS88** [PatrickAlphaC/all-on-chain-generated-nft#7]
Hi Patrick - first of all, amazing tutorial! Thanks for sharing it on YT.

Deployed and verified successfully on Rinkeby, then went to Etherscan to call directly create( ) and the tx failed with error "Exception thrown in contract code".

Tested also with your contract in Polygon and got the same error: https://polygonscan.com/tx/0x66bb8c33fa94f3d33505cb6ba3dc36027aac8eaec5308e9e2c764004db6d3af1

Does it make sense what I'm trying to do? I wanted to first call create( ) and then finishMint( ) directly from Etherscan.

**Comment by PatrickAlphaC** [comment]
You need to send it some LINK :)
